import { DataTypes } from "sequelize";
import { sequelize } from "../config/db.js";

export const Student = sequelize.define("Student", {
  id: { type: DataTypes.INTEGER, primaryKey: true },
  academicHouse: DataTypes.STRING,
  birthCounty: DataTypes.STRING,
  birthplace: DataTypes.STRING,
  boardingHouse: DataTypes.STRING,
  boardingStatus: DataTypes.STRING,
  dob: DataTypes.DATEONLY,
  enrolmentDate: DataTypes.DATEONLY,
  enrolmentStatus: DataTypes.STRING,
  enrolmentTerm: DataTypes.STRING,
  enrolmentYear: DataTypes.INTEGER,
  ethnicity: DataTypes.STRING,
  familyId: DataTypes.INTEGER,
  forename: DataTypes.STRING,
  formGroup: DataTypes.STRING,
  fullName: DataTypes.STRING,
  futureSchoolId: DataTypes.INTEGER,
  gender: DataTypes.STRING,
  homeAddresses: DataTypes.JSON,
  initials: DataTypes.STRING,
  isVisaRequired: DataTypes.BOOLEAN,
  labelSalutation: DataTypes.STRING,
  languages: DataTypes.JSON,
  lastUpdated: DataTypes.DATE,
  latestPhotoId: DataTypes.INTEGER,
  leavingDate: DataTypes.DATEONLY,
  leavingReason: DataTypes.STRING,
  leavingYearGroup: DataTypes.STRING,
  letterSalutation: DataTypes.STRING,
  middlenames: DataTypes.STRING,
  mobileNumber: DataTypes.STRING,
  nationalities: DataTypes.JSON,
  officialName: DataTypes.STRING,
  personalEmailAddress: DataTypes.STRING,
  personGuid: DataTypes.STRING,
  personId: DataTypes.INTEGER,
  preferredName: DataTypes.STRING,
  previousName: DataTypes.STRING,
  religion: DataTypes.STRING,
  removalGrounds: DataTypes.STRING,
  residentCountry: DataTypes.STRING,
  schoolCode: DataTypes.STRING,
  schoolEmailAddress: DataTypes.STRING,
  schoolId: DataTypes.STRING,
  surname: DataTypes.STRING,
  systemStatus: DataTypes.STRING,
  title: DataTypes.STRING,
  tutorEmployeeId: DataTypes.INTEGER,
  uniquePupilNumber: DataTypes.STRING,
  yearGroup: DataTypes.INTEGER,
}, {
  tableName: "students",
  timestamps: false,
});
