import { DataTypes } from "sequelize";
import { sequelize } from "../config/db.js";

export const Withdrawal = sequelize.define("Withdrawal", {
  admissionStatus: DataTypes.STRING,
  boardingStatus: DataTypes.STRING,
  customFields: DataTypes.JSON,
  enquiryDate: DataTypes.DATEONLY,
  enrolmentDate: DataTypes.DATEONLY,
  enrolmentYear: DataTypes.INTEGER,
  enrolmentYearGroup: DataTypes.INTEGER,
  forename: DataTypes.STRING,
  fullName: DataTypes.STRING,
  futureSchoolId: DataTypes.INTEGER,
  gender: DataTypes.STRING,
  initials: DataTypes.STRING,
  languages: DataTypes.JSON,
  lastUpdated: DataTypes.DATE,
  leavingDate: DataTypes.DATEONLY,
  leavingReason: DataTypes.STRING,
  leavingTerm: DataTypes.STRING,
  leavingYear: DataTypes.INTEGER,
  leavingYearGroup: DataTypes.INTEGER,
  middlenames: DataTypes.STRING,
  nationalities: DataTypes.JSON,
  officialName: DataTypes.STRING,
  personGuid: DataTypes.STRING,
  personId: { type: DataTypes.INTEGER, primaryKey: true },
  preferredName: DataTypes.STRING,
  registeredDate: DataTypes.DATEONLY,
  schoolCode: DataTypes.STRING,
  schoolId: DataTypes.STRING,
  surname: DataTypes.STRING,
  systemStatus: DataTypes.STRING,
  title: DataTypes.STRING,
  visitDate: DataTypes.DATEONLY,
  yearGroup: DataTypes.INTEGER,
}, {
  tableName: "withdrawals",
  timestamps: false,
});
